spring.application.name=BatPonto
# Configura\uFFFD\uFFFDo do DataSource (Conex\uFFFDo)
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura\uFFFD\uFFFDo do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET}
api.security.token.expiration-seconds=3600

app.superadmin.email=${ADMIN_USER_EMAIL}
app.superadmin.password=${ADMIN_USER_PASSWORD}
app.superadmin.name=ADMIN
